import Head from 'next/head';
import Link from "next/link";
import { useRequireAuth } from "../../hooks/useRequireAuth";
import LoadingPage from "../../components/loading-page";

import ProfileDropDownMenu from "../../components/profileDropdownMenu";
import ThemeSwitcher from '../../components/themeSwitcher';
import AppLogo from '../../components/appLogo';
import AppFooter from "../../components/appFooter";
import { useEffect } from 'react';

function Profile() {
  const auth = useRequireAuth();

  const { user } = auth;

  useEffect(async () => {
    if(auth.token) await auth.getProfile();
  }, [auth.token])

  if (!auth.token || !auth.user) return <LoadingPage />

  return (
    <div>
      <Head>
        <title>Profile</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container px-4 lg:px-0 mx-auto h-screen flex flex-col items-center w-full">
        <header className="w-full py-2">
          <div className="flex w-full items-center justify-between">
            <AppLogo />
            <div className="flex items-center">
              <div className="mr-6 flex items-center">
                <ThemeSwitcher />
              </div>
              <ProfileDropDownMenu username={user.name} photo={user.photo} />
            </div>
          </div>
        </header>

        <div className="md:w-10/12 lg:w-8/12 py-8 w-full flex flex-col items-center">
          <div className="pb-8 mt-4 flex flex-col items-center">
            <h2 className="text-2xl md:text-4xl text-gray-6 dark:text-white">Profile Info</h2>
            <h4 className="text-gray-3 text-sm md:text-base mt-2 dark:text-gray-1">Basic info, like your name and photo</h4>
          </div>

          <section className="w-full md:border rounded-lg">
            <header className="entry-info">
              <div>
                <h2 className="text-xl text-gray-6 dark:text-white">Profile</h2>
                <span className="text-gray-3 mt-2 leading-tight block text-sm dark:text-gray-5">Some info maybe visible to other people.</span>
              </div>

              <button className="outline-none rounded-lg text-gray-3 ml-2 text-sm dark:text-gray-5 focus:outline-none border text-center px-6 py-2">
                <Link href="/profile/edit">edit</Link>
              </button>
            </header>
            <div className="entry-info">
              <div className="entry-label">
                photo
              </div>
              <div className="entry-value">
                <img src={user.photo} alt="user's profile image" className="w-3/12 text-xs h-auto object-cover" />
              </div>
            </div>
            <div className="entry-info">
              <div className="entry-label">
                name
              </div>
              <div className="entry-value">
                {user.name}
              </div>
            </div>
            <div className="entry-info">
              <div className="entry-label">
                bio
              </div>
              <div className="entry-value text-right md:text-left">
                {user.bio}
              </div>
            </div>

            <div className="entry-info">
              <div className="entry-label">
                phone
              </div>
              <div className="entry-value">
                {user.phone}
              </div>
            </div>
            <div className="entry-info border-none">
              <div className="entry-label">
                email
              </div>
              <div className="entry-value">
                {user.email}
              </div>
            </div>
          </section>

          <AppFooter />
        </div>
      </main>
    </div>
  )
}

export default Profile;
