import Head from 'next/head';
import { useRouter } from "next/router";

import { useRequireAuth } from "../hooks/useAuth";
import LoadingPage from "../components/loading-page";


function Home() {
  const router = useRouter();
  const auth = useRequireAuth();

  if (!auth.token) return (
    <>
      <Head>
        <title>Authentication App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LoadingPage />
    </>
  )
  router.replace("/profile");

  return (<></>)
}

export default Home;
