import Head from 'next/head';
import { useRequireAuth } from "../hooks/useRequireAuth";
import LoadingPage from "../components/loading-page";

function Profile() {
  const auth = useRequireAuth();

  if(!auth.token) return <LoadingPage />

  return (
    <div>
      <Head>
        <title>Profile</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex items-center justify-center h-screen w-full">
        <h1 className="text-gray-700">
          Hello, world!
        </h1>
      </main>
    </div>
  )
}

export default Profile;
